### ISSUE TITLE
framework doesn't wait for all stdout to return

### ISSUE THREAD

**Issue by bhenderson** [yp-engineering/mesos-runonce#11]
If the command is particularly noisy (testable using find /), the framework will finish before all the output can be returned and will get cut off.

I'm working on a patch.

**Comment by hekaldama** [comment]
Interesting. Does WaitGroup need to be in the main()?

**Comment by bhenderson** [comment]
I started a branch fix_output_waiting. When changing the command to "find /" and comparing with `docker run alpine find /` we get differences, so I don't think it's working properly yet.

**Comment by hekaldama** [comment]
Using:

```
./mesos-runonce -master=mesos-master:5050 \
  -address=$(ip route get 8.8.8.8 | grep -o src.* | grep -oE "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+") \
  -docker-cmd="find / | grep -vE '/sys|/net|/proc' | sort" \
  -docker-image=alpine \
  -principal=principal \
  -secret-file=<(printf something-secret) \
  -force-pull=true > alpine_mesos_find_root_sorted1 && \
./mesos-runonce -master=mesos-master:5050 \
  -address=$(ip route get 8.8.8.8 | grep -o src.* | grep -oE "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+") \
  -docker-cmd="find / | grep -vE '/sys|/net|/proc' | sort" \
  -docker-image=alpine \
  -principal=principal \
  -secret-file=<(printf something-secret) \
  -force-pull=true > alpine_mesos_find_root_sorted2 && \
diff alpine_mesos_find_root_sorted1 alpine_mesos_find_root_sorted2
```

for testing and got only the expected diff of what host I was running on and such. You can see that in the `find /` command I am ignoring certain directories that will always be different between runs / hosts.

I think this is resolved.
